version = 0.1

[default.global.parameters]
stack_name = "nouriq-api"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
region = "ap-south-1"
resolve_s3 = true
